# Generated by Django 6.0 on 2025-12-08 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название вакансии')),
                ('company', models.CharField(max_length=100, verbose_name='Компания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary', models.PositiveIntegerField(default=0, verbose_name='Зарплата')),
                ('employment_type', models.CharField(default='Полная занятость', max_length=50, verbose_name='Тип занятости')),
                ('location', models.CharField(default='Не указано', max_length=100, verbose_name='Локация')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
