# Generated by Django 6.0 on 2026-01-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_add_historical_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalapplication',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalcompany',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalcompany',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalresume',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalresume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='historicalresume',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalstudent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='historicalvacancy',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalvacancy',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, to='vacancies.skill', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
